services:
  - type: web
    name: yt-transcript-api
    runtime: python
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg && pip install yt-dlp
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
