services:
  - type: web
    name: youtube-transcript-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
        envVars:
      - key: PROXY_URL
        value: http://YOUR_PROXY_IP:PORT
    
